version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: lib_db_container
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8

    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - container-link

  app:
    build: .
    container_name: lib_app_container
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: 
      npm start
    networks:
      - container-link
    depends_on:
      - mysql

networks:
  container-link:
volumes:
  mysqldata:
