version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: lib_db_container
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - container-link

  app:
    build: .
    container_name: lib_app_container
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm start
    networks:
      - container-link
    depends_on:
      - mysql

networks:
  container-link:

volumes:
  mysqldata:
